version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/run_process
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_service
      timeout: 300
      runas: root
